"""
Report generation for BAS engagements.

Generates structured reports mapping findings to MITRE ATT&CK techniques
and providing remediation guidance via AI analysis.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any

from jinja2 import Environment, BaseLoader


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class Finding:
    """A single security finding from a BAS operation."""
    finding_id: str
    title: str
    severity: Severity
    module: str
    target: str
    description: str
    evidence: str
    mitre_technique_id: str = ""
    mitre_technique_name: str = ""
    remediation: str = ""
    raw_response: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class EngagementReport:
    """Complete report for a BAS engagement."""
    engagement_id: str
    engagement_name: str
    start_time: datetime
    end_time: datetime
    scope_summary: dict[str, Any]
    findings: list[Finding] = field(default_factory=list)
    modules_executed: list[str] = field(default_factory=list)
    targets_tested: list[str] = field(default_factory=list)
    statistics: dict[str, Any] = field(default_factory=dict)
    ai_analysis: str = ""

    @property
    def severity_counts(self) -> dict[str, int]:
        counts = {s.value: 0 for s in Severity}
        for f in self.findings:
            counts[f.severity.value] += 1
        return counts


REPORT_TEMPLATE = """
# BAS Engagement Report
## {{ report.engagement_name }}

**Engagement ID:** {{ report.engagement_id }}
**Period:** {{ report.start_time.isoformat() }} - {{ report.end_time.isoformat() }}
**Generated:** {{ now }}

---

## Executive Summary

- **Total Findings:** {{ report.findings | length }}
- **Critical:** {{ report.severity_counts.critical }}
- **High:** {{ report.severity_counts.high }}
- **Medium:** {{ report.severity_counts.medium }}
- **Low:** {{ report.severity_counts.low }}
- **Informational:** {{ report.severity_counts.info }}

**Modules Executed:** {{ report.modules_executed | join(', ') }}
**Targets Tested:** {{ report.targets_tested | length }}

---

## Scope

```json
{{ scope_json }}
```

---

## Findings

{% for finding in report.findings %}
### {{ finding.finding_id }}: {{ finding.title }}

| Field | Value |
|-------|-------|
| **Severity** | {{ finding.severity.value | upper }} |
| **Module** | {{ finding.module }} |
| **Target** | {{ finding.target }} |
| **MITRE ATT&CK** | {{ finding.mitre_technique_id }} - {{ finding.mitre_technique_name }} |

**Description:**
{{ finding.description }}

**Evidence:**
```
{{ finding.evidence }}
```

**Remediation:**
{{ finding.remediation }}

---
{% endfor %}

{% if report.ai_analysis %}
## AI Analysis

{{ report.ai_analysis }}

---
{% endif %}

## Statistics

| Metric | Value |
|--------|-------|
{% for key, value in report.statistics.items() %}
| {{ key }} | {{ value }} |
{% endfor %}

---
*Report generated by BAS Engine v{{ version }}*
"""


class ReportGenerator:
    """Generates engagement reports in multiple formats."""

    def __init__(self, ai_analyzer: Any = None):
        self._ai_analyzer = ai_analyzer
        self._env = Environment(loader=BaseLoader())
        self._template = self._env.from_string(REPORT_TEMPLATE)

    def generate_markdown(self, report: EngagementReport) -> str:
        """Generate a Markdown report."""
        return self._template.render(
            report=report,
            now=datetime.now().isoformat(),
            scope_json=json.dumps(report.scope_summary, indent=2),
            version="0.1.0",
        )

    def generate_json(self, report: EngagementReport) -> str:
        """Generate a JSON report for integration with other tools."""
        return json.dumps({
            "engagement_id": report.engagement_id,
            "engagement_name": report.engagement_name,
            "start_time": report.start_time.isoformat(),
            "end_time": report.end_time.isoformat(),
            "scope": report.scope_summary,
            "statistics": report.statistics,
            "severity_counts": report.severity_counts,
            "findings": [
                {
                    "id": f.finding_id,
                    "title": f.title,
                    "severity": f.severity.value,
                    "module": f.module,
                    "target": f.target,
                    "description": f.description,
                    "evidence": f.evidence,
                    "mitre_technique_id": f.mitre_technique_id,
                    "mitre_technique_name": f.mitre_technique_name,
                    "remediation": f.remediation,
                    "timestamp": f.timestamp.isoformat(),
                }
                for f in report.findings
            ],
            "ai_analysis": report.ai_analysis,
            "modules_executed": report.modules_executed,
            "targets_tested": report.targets_tested,
        }, indent=2)

    def save_report(self, report: EngagementReport, output_dir: Path, formats: list[str] | None = None) -> list[Path]:
        """Save report to disk in specified formats."""
        formats = formats or ["markdown", "json"]
        output_dir.mkdir(parents=True, exist_ok=True)
        saved: list[Path] = []

        if "markdown" in formats:
            md_path = output_dir / f"{report.engagement_id}_report.md"
            md_path.write_text(self.generate_markdown(report))
            saved.append(md_path)

        if "json" in formats:
            json_path = output_dir / f"{report.engagement_id}_report.json"
            json_path.write_text(self.generate_json(report))
            saved.append(json_path)

        return saved

    async def enrich_with_ai(self, report: EngagementReport) -> EngagementReport:
        """Use AI analyzer to add remediation guidance and analysis."""
        if not self._ai_analyzer:
            return report

        # AI analysis of overall findings
        report.ai_analysis = await self._ai_analyzer.analyze_findings(report.findings)

        # AI remediation suggestions per finding
        for finding in report.findings:
            if not finding.remediation:
                finding.remediation = await self._ai_analyzer.suggest_remediation(finding)

        return report
